language: ruby
rvm:
- 2.3.4
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
  provider: rubygems
  api_key:
    secure: upZhf4cvA1wg5GkRqfR7qQvq70Nk3NA8C2IZNkinq8GhvL8nA9+NzmIdKpRqZ9tO5izT0LuiBp3z06vpsmWKVMOSWOjx5d6hhTtA/CCCB7zGJEaRDKZ3a7/LbeRoc4L764Ayl3AUMHThjkAhGij8X5FFYLAVXCJwnOP1/FMyBiOhI02n7NocJjGlvCMWjiWZUcMxiyenLwUkuYGVqBkvK/JTzxvthdsGzkpb29oFhimeQGHGw9lr04ITatb56lp+NWJg+UZYyI5nKnAN29mgLdINjRKMVo1prIX6E6aZCPT9vkR+bz2B89mcSfl/0I+cmcqCWtmLhTSpING/HgXzyNRUKN4cprTAxbrCi4SpSaVfaTpKe3vS23kZJfD9yYx3IY/bEXwFounWZsDbfFDLXlAaes8kViRQNftR8Khy2Lf1Ig7UeseILQ9lXfDmEG9ZbUMQSOyuzTviy/8PN665R74HKaNkswKzt+uqT+SNQ6KOv7QumqBDL+ZPTqI9+a8mpBRB2kq8/A0ojJCNVX5Dnpu7/OmqMJY48WMyMROOy2zK8CcsgWoMD1m8hMczAngRYDv4H2+DvXWFzig0Nvp+ZrEcoiV2MoF5psJzMZEHloor7RbsVFmqwyMph9V3pp7ci+pVekgPo9p4AesPBm2Z2f1OvuT7bdM7Cn4OUbj1290=
  gem: pwork
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.4"
env:
  global:
    secure: DmNYliyOnbVHQpWjmhsjmjOhZUjZpDDoZr2LBkKMoIJZnpVXlP4RFlPTHeMSo37Wb8a9LRmpntMtkPAdoYgXW41i4QyyLrY40PegAwFRomLfQdcUCTr9Vmi1mE9jkNS57zJW18ac7PwIQemfxj5vunB1kVROUitlAxkNFZoXMF1r9lxSVyZBwYyiTs42kinFNGG2uaDeaH9M0ciqw1gXBlB2Cwp+yZWhDSMJlMH9uevkCbiYk502DTIDPktaUEJPxTnNmTsnM1h1KeclG5uo2r23diSgMYsz79gatwlzX/yAeZoTNSa8PL7ZaPlAfpZh6p3YJ04LY3uxO9FhbYLgKcjYpSPW6zegUrdyjt3v1EPcDfxUIDRIzhlm+KmOaxgJiJCc8t5eGAlqIbHSOofnNyzX565Rc/5noopO2y+GztamAm4w3bnqMV6R7Cdgyfin2BraPqLxhkQY9o7nqNhfw7ackX5Cipno3GC8iNIn7jrKb9MaRNR3+3iqhUO7lJJN/H+OB6FP1v1E/N0RNLX7OiDWmfMLRzmkjMu599h/WWoACbEatfTeHpyJJFVEKopivA3Yx0kG2F60lQWlXtAnxMm0zaqWVd3jle2a6XD8FTPfxCDCxS5s7N7eC5NmmAAeScxxj3IxMgyY7m5g7573hod+3ctQfqzZ08+Ui8kL0JI=
