testrunner:
  image: 522104923602.dkr.ecr.eu-west-1.amazonaws.com/sageone/ruby:20170831
  container_name: testrunner
  command: bash -c "./scripts/container_loop.sh"
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../.:/gem_src

testrunner2:
  image: 522104923602.dkr.ecr.eu-west-1.amazonaws.com/sageone/jruby:20170623
  container_name: testrunner_jruby
  command: bash -c "./scripts/container_loop.sh"
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../.:/gem_src